packages:
  # Include all of the core configuration
  core: !include buderus-km271_en.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    #name: esphome.project-template
    name: esphome.km271-wifi
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  #package_import_url: github://esphome/esphome-project-template/project-template-esp32-adopt.yaml@main
  package_import_url: github://the78mole/esphome_components/components/km271_wifi/km271-for-friends.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: improvble
  authorized_duration: 120s
  status_indicator: led3
  identify_duration: 60s

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
